package com.randevupazaryeri.common.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    BUSINESS_RULE_VIOLATION,
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,
    APPOINTMENT_SLOT_UNAVAILABLE,
    INVALID_APPOINTMENT,
    CONFLICT,
    INTERNAL_ERROR,
    INVALID_IMAGE,
    FILE_TOO_LARGE,
    UNSUPPORTED_MEDIA_TYPE,
    RATE_LIMITED,
    STORAGE_ERROR
}
